Ci/cd test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,25 +10,35 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout Code
-      uses: actions/checkout@v2
+      - name: Checkout Code
+        uses: actions/checkout@v2
 
-    - name: Install Project Dependencies
-      run: npm ci
-      working-directory: ./Portfolio-Website
+      - name: Install Node.js and npm
+        uses: actions/setup-node@v2
+        with:
+          node-version: '14'
 
-    - name: Build Angular Project
-      run: npx ng build --configuration production
-      working-directory: ./Portfolio-Website
+      - name: Install Project Dependencies
+        run: npm ci
+        working-directory: ./Portfolio-Website
 
-    - name: Setup SSH
-      uses: webfactory/ssh-agent@v0.5.4
-      with:
-        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+      - name: Build Angular Project
+        run: npx ng build --configuration production
+        working-directory: ./Portfolio-Website
 
-    - name: Deploy to Server
-      run: |
-        scp -o StrictHostKeyChecking=no -r ./Portfolio-Website/dist/portfolio-website/* srikar@76.84.212.254:/path/to/nginx/html
-        ssh -o StrictHostKeyChecking=no srikar@76.84.212.254 << 'EOF'
-          /home/srikar/deploy.sh
-        EOF
+      - name: Setup SSH
+        uses: webfactory/ssh-agent@v0.5.4
+        with:
+          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+
+      - name: Deploy to Server
+        run: |
+          scp -o StrictHostKeyChecking=no -r ./Portfolio-Website/dist/portfolio-website/* srikar@76.84.212.254:/path/to/nginx/html
+          ssh -o StrictHostKeyChecking=no srikar@76.84.212.254 '/home/srikar/deploy.sh'
+
+      - name: Check SSH and SCP exit codes
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Error: SSH or SCP command failed with exit code $?"
+            exit 1
+          fi
